### ISSUE TITLE
NoClassDefFoundError when running a search using a Hits view

### ISSUE THREAD

**Issue by sodle** [algolia/instantsearch-android#104]
I'm trying to integrate the code from your Android tutorial into my app. When running `helper.search()`, the app crashes, failing to find a class def for "com.android.databinding.library.baseAdapters.DataBinderMapperImpl".

My app uses Kotlin and AndroidX, if it makes any difference.

**Do you want to request a *feature* or report a *bug*?**
Bug

**Bug: What is the current behavior?**
Activity crashes with stack trace
```
java.lang.NoClassDefFoundError: Failed resolution of: Lcom/android/databinding/library/baseAdapters/DataBinderMapperImpl;
        at com.algolia.instantsearch.DataBinderMapperImpl.collectDependencies(DataBinderMapperImpl.java:71)
        at androidx.databinding.MergedDataBinderMapper.addMapper(MergedDataBinderMapper.java:58)
        at androidx.databinding.MergedDataBinderMapper.addMapper(MergedDataBinderMapper.java:60)
        at androidx.databinding.DataBinderMapperImpl.<init>(DataBinderMapperImpl.java:5)
        at androidx.databinding.DataBindingUtil.<clinit>(DataBindingUtil.java:32)
        at androidx.databinding.DataBindingUtil.inflate(DataBindingUtil.java:95)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onCreateViewHolder(Hits.java:459)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onCreateViewHolder(Hits.java:424)
        at androidx.recyclerview.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6794)
        at androidx.recyclerview.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5975)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5858)
        at androidx.recyclerview.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5854)
        at androidx.recyclerview.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2230)
        at androidx.recyclerview.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1557)
        at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1517)
        at androidx.recyclerview.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:612)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3924)
        at androidx.recyclerview.widget.RecyclerView.dispatchLayout(RecyclerView.java:3641)
        at androidx.recyclerview.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1858)
        at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5044)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1004)
        at android.view.Choreographer.doCallbacks(Choreographer.java:816)
        at android.view.Choreographer.doFrame(Choreographer.java:748)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:990)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6863)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:537)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.android.databinding.library.baseAdapters.DataBinderMapperImpl" on path
```

**Bug: What is the expected behavior?**
Hits view loads with search results

**Comment by sodle** [comment]
Thank you! I've starred the issue.

**Comment by PLNech** [comment]
Hi again, thanks for starring the issue :slightly_smiling_face: 

We are going to release a new artifact refactored with `androidX` to unblock you until the bug is resolved. To avoid forcing our other customers to update, we’ll likely keep `instantsearch-android` on `support.v7` while releasing a new `instantsearch-androidx` based on `AndroidX` that you’ll be able to use in your projects.

This situation with two different artifacts will be temporary, and will resolve as soon as:

- Google fixes the `jetifier` issue, allowing us to ship the initial support.v7 codebase for both `support.v7` users and AndroidX users like you
- AndroidX becomes the norm and we can drop support of support.v7 package

When either one happens, we’ll delete the `instantsearch-androidx` artifacts and will be back to simply exposing `instantsearch-android`.

**Comment by sodle** [comment]
Thanks for all of your support on this. Let me know when the new artifacts are up and what Gradle package I should be importing.

Best of luck with the Jetifier issue, and if you're in the US, happy Thanksgiving!

**Comment by PLNech** [comment]
You're welcome! I'll update you here as soon as it is available :)

Thanks, I'm in France but am lucky to have US coworkers with whom I can share a Potluck :yum: 
Happy Thanksgiving to you too!

**Comment by PLNech** [comment]
Hi @sodle, our **InstantSearch AndroidX** artifacts are now available! 
You can use these within your AndroidX Application as long as the [Jetifier <> Android.Databinding bug](https://issuetracker.google.com/issues/119776863) is unsolved.

To use the AndroidX version of our library, you shall use these artifacts:

```groovy
implementation 'com.algolia:instantsearch-androidx:1.14.0' // Full library
// OR INSTEAD
implementation 'com.algolia:instantsearch-androidx-core:1.14.0' // Core library (no Widgets/databinding logic)
```

You can check the [`androidX` branch of our `instantsearch-android-mvp` project](https://github.com/algolia/instantsearch-android-mvp/tree/androidX), which follows this logic to build with InstantSearch and AndroidX.

Updates will be released there as well as on the original `instantsearch-android` artifacts until the situation is resolved and we can get back to a single line of artifacts!
