### ISSUE TITLE
Fatal Exception: java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap

### ISSUE THREAD

**Issue by squarenotch** [algolia/instantsearch-android#150]
**Describe the bug 🐛**
Set up a very simple test project. When scrolling down the results, the app crashes with the following error:

java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap

**To Reproduce 🔍**
**build.gradle**
`implementation 'com.algolia:instantsearch-androidx:1.15.2'`

**fragment**
```
searcher = Searcher.create(ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY, ALGOLIA_INDEX_NAME);
        helper = new InstantSearch(v, searcher);
        helper.registerWidget(v.findViewById(R.id.hits));
        helper.search("cars");`
```

**fragment layout**
```
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:algolia="http://schemas.android.com/apk/res-auto"
    android:orientation="vertical" android:layout_width="match_parent"
    android:layout_height="match_parent">

    <com.algolia.instantsearch.ui.views.Hits
        android:id="@+id/hits"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        algolia:itemLayout="@layout/hits_item"/>


</LinearLayout>
```

**hit item layout**

```
<layout xmlns:algolia="http://schemas.android.com/apk/res-auto">
<LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
    android:orientation="horizontal"
    android:layout_width="match_parent"
    android:layout_height="wrap_content">
    <ImageView
        android:id="@+id/product_image"
        android:layout_width="match_parent"
        android:layout_height="wrap_content"
        android:layout_margin="1dp"
        android:scaleType="fitCenter"
        algolia:attribute='@{"publicUrl"}'/>

</LinearLayout>
</layout>
```

**Expected behavior 💭**
Scroll through images without crashing

**Environment:**
 - compileSdkVersion 28
 - targetSdkVersion 28

**Comment by PLNech** [comment]
Hi @squarenotch, thanks for sharing this! We'll investigate and let you know as we make progress.

**Comment by squarenotch** [comment]
Hi @PLNech. I am just wondering if you were able to reproduce the issue? This is currently affecting a development push and I am needing to make the decision whether or not to use the components from Algolia or develop our own. An update would be great. Thanks.

**Comment by PLNech** [comment]
Hi @squarenotch, for now I'm unable to reproduce the issue. [Here's a project](https://msg.algolia.com/getmsg?token=ad38e132-e774-58c4-5d4b-72fa8a4e9246&filetoken=d0d3c62c-83af-0a33-cc2c-df743083c01d&filename=Issue150Repro.zip) I setup following your _Steps to reproduce_, where scrolling the `Hits` works for me:
<img src="https://user-images.githubusercontent.com/1821404/55004485-9c953600-4fda-11e9-8c58-05180db726cd.gif" alt="GIF of scrolling app" heigth="200"/>

I wonder if the issue could come from the way you instantiate `InstantSearch`: what is `v` in your code?
The `InstantSearch(widget, searcher)` constructor expects an `AlgoliaWidget` as the first parameter, which in your case should be the `Hits` widget in your layout. This means I would expect your code to rather look like this:
```diff
searcher = Searcher.create(ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY, ALGOLIA_INDEX_NAME);
+       hits = (Hits) v.findViewById(R.id.hits);
-       helper = new InstantSearch(v, searcher);
+       helper = new InstantSearch(hits, searcher);
-       helper.registerWidget(v.findViewById(R.id.hits)); // Not needed as registered at instantiation
        helper.search("cars");`
```

- Can you try this suggestion and see if it resolves the issue?
- If not, can you share the whole file where you instantiate this Searcher? Likewise, a full stacktrace of the exception you are hitting would be helpful.

**Comment by squarenotch** [comment]
Thanks @PLNech . I have been trying lots of different implementations, all with the same result unfortunately. Originally the hits and searcher were contained within a fragment so I pulled the code out and used an Activity, just in case that might have caused some problems. I can scroll slowly without issues but if I scroll fast and pull in lots of images quickly it causes the error.

File attached.

Stack Trace:

`2019-04-02 23:08:36.697 27073-27073/com.andronicus.coolwallpapers E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.andronicus.coolwallpapers, PID: 27073
    java.lang.RuntimeException: Canvas: trying to use a recycled bitmap android.graphics.Bitmap@5eec79
        at android.graphics.BaseCanvas.throwIfCannotDraw(BaseCanvas.java:62)
        at android.view.DisplayListCanvas.throwIfCannotDraw(DisplayListCanvas.java:226)
        at android.view.RecordingCanvas.drawBitmap(RecordingCanvas.java:98)
        at android.graphics.drawable.BitmapDrawable.draw(BitmapDrawable.java:545)
        at android.widget.ImageView.onDraw(ImageView.java:1342)
        at android.view.View.draw(View.java:20207)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.updateDisplayListIfDirty(View.java:19073)
        at android.view.View.draw(View.java:19935)
        at android.view.ViewGroup.drawChild(ViewGroup.java:4333)
        at androidx.recyclerview.widget.RecyclerView.drawChild(RecyclerView.java:4820)
        at android.view.ViewGroup.dispatchDraw(ViewGroup.java:4112)
        at android.view.View.draw(View.java:20210)
        at androidx.recyclerview.widget.RecyclerView.draw(RecyclerView.java:4219)
        at android.view.View.updateDisplayListIfDirty(View.java:19082)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ViewGroup.recreateChildDisplayList(ViewGroup.java:4317)
        at android.view.ViewGroup.dispatchGetDisplayList(ViewGroup.java:4290)
        at android.view.View.updateDisplayListIfDirty(View.java:19042)
        at android.view.ThreadedRenderer.updateViewTreeDisplayList(ThreadedRenderer.java:686)
        at android.view.ThreadedRenderer.updateRootDisplayList(ThreadedRenderer.java:692)
        at android.view.ThreadedRenderer.draw(ThreadedRenderer.java:801)
        at android.view.ViewRootImpl.draw(ViewRootImpl.java:3311)
        at android.view.ViewRootImpl.performDraw(ViewRootImpl.java:3115)
        at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2484)
        at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1460)
        at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7183)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:949)
        at android.view.Choreographer.doCallbacks(Choreographer.java:761)
        at android.view.Choreographer.doFrame(Choreographer.java:696)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:935)
        at android.os.Handler.handleCallback(Handler.java:873)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:193)
        at android.app.ActivityThread.main(ActivityThread.java:6718)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:858)
    `

[Activity_SearchResults.txt](https://github.com/algolia/instantsearch-android/files/3036068/Activity_SearchResults.txt)

**Comment by PLNech** [comment]
Hello @squarenotch, thanks for your patience. After a few tries replicating your situation, I'm afraid I still cannot reproduce the bug you reported. [Here is a project](https://github.com/algolia/instantsearch-android/files/3068032/Issue150Repro.zip) replicating to the best of my knowledge your code, with the `Activity_SearchResults.txt` you shared.

- Can you try running this project on your device/emulator and let me know if you encounter the same issue? If yes, we should be able to pinpoint the context in which it appears. If not, could you share the smallest subset of your project that would be a working app demonstrating the issue so that I can run it on my side on different devices? 

- In the meantime, a workaround would be to [**avoid**](https://github.com/makeabledk/instantsearch-android/blob/master/ui/src/main/java/com/algolia/instantsearch/ui/views/Hits.java#L495) the [Bitmap loading logic of the `Hits`](https://github.com/makeabledk/instantsearch-android/blob/master/ui/src/main/java/com/algolia/instantsearch/ui/views/Hits.java#L505-L537) by implementing `AlgoliaHitView` in your ImageView. This way you'll be able to manually define the logic for loading images, which should let you avoid the root cause of this bug.

**Comment by PLNech** [comment]
_Closing as stale, feel free to reopen and reply to my last message if you're still facing this bug._
