### ISSUE TITLE
Crash on starting search: java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;)V in class Lkotlinx/serialization/internal/SerialClassDescImpl

### ISSUE THREAD

**Issue by fobo66** [algolia/instantsearch-android#198]
**Describe the bug 🐛**

When I start search, app crashes immediately with the following stacktrace:

```
2020-05-08 17:46:14.375 13375-13375/com.bookcrossing.mobile E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.bookcrossing.mobile, PID: 13375
    java.lang.NoSuchMethodError: No direct method <init>(Ljava/lang/String;Lkotlinx/serialization/internal/GeneratedSerializer;)V in class Lkotlinx/serialization/internal/SerialClassDescImpl; or its super classes (declaration of 'kotlinx.serialization.internal.SerialClassDescImpl' appears in /data/app/com.bookcrossing.mobile-B9gM-7sEV1YAj6rUbzWThA==/base.apk!classes5.dex)
        at com.algolia.search.model.APIKey$Companion.<clinit>(Unknown Source:5)
        at com.algolia.search.model.APIKey.<clinit>(Unknown Source:0)
        at com.bookcrossing.mobile.presenters.SearchPresenter.<init>(SearchPresenter.kt:56)
        at com.bookcrossing.mobile.presenters.SearchPresenter_Factory.newInstance(SearchPresenter_Factory.java:29)
        at com.bookcrossing.mobile.presenters.SearchPresenter_Factory.get(SearchPresenter_Factory.java:21)
        at com.bookcrossing.mobile.presenters.SearchPresenter_Factory.get(SearchPresenter_Factory.java:8)
        at com.bookcrossing.mobile.ui.search.SearchFragment$presenter$2.invoke(SearchFragment.kt:45)
        at com.bookcrossing.mobile.ui.search.SearchFragment$presenter$2.invoke(SearchFragment.kt:41)
        at moxy.ktx.MoxyKtxDelegate$field$1.providePresenter(MoxyKtxDelegate.kt:18)
        at moxy.MvpProcessor.getMvpPresenter(MvpProcessor.java:48)
        at moxy.MvpProcessor.getMvpPresenters(MvpProcessor.java:88)
        at moxy.MvpDelegate.onCreate(MvpDelegate.java:144)
        at moxy.MvpAppCompatFragment.onCreate(MvpAppCompatFragment.java:29)
        at androidx.fragment.app.Fragment.performCreate(Fragment.java:2684)
        at androidx.fragment.app.FragmentStateManager.create(FragmentStateManager.java:280)
        at androidx.fragment.app.FragmentManager.moveToState(FragmentManager.java:1175)
        at androidx.fragment.app.FragmentManager.addAddedFragments(FragmentManager.java:2224)
        at androidx.fragment.app.FragmentManager.executeOpsTogether(FragmentManager.java:1997)
        at androidx.fragment.app.FragmentManager.removeRedundantOperationsAndExecute(FragmentManager.java:1953)
        at androidx.fragment.app.FragmentManager.execPendingActions(FragmentManager.java:1849)
        at androidx.fragment.app.FragmentManager$4.run(FragmentManager.java:413)
        at android.os.Handler.handleCallback(Handler.java:883)
        at android.os.Handler.dispatchMessage(Handler.java:100)
        at android.os.Looper.loop(Looper.java:214)
        at android.app.ActivityThread.main(ActivityThread.java:7356)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:492)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:930)
```

From what I can see, there is something with `APIKey` serializer and how it's bundled inside dex

You can check source code [here](https://github.com/fobo66/BookcrossingMobile/blob/master/app/src/main/java/com/bookcrossing/mobile/presenters/SearchPresenter.kt)

**To Reproduce 🔍**
1. Open app
2. Click on search icon
3. See error

**Expected behavior 💭**
Search view should appear

**Environment:**
 - OS: Android 10, AGP 4.1.0-alpha09 (but checked also on 3.6.3, 4.0.0-beta03, same crash)
 - Library Version 2.3.1 (but checked also on 2.2.0, same crash)

**Additional context**

**Comment by fobo66** [comment]
I see now that it's a bug in `instantsearch-client-kotlin` library, so you can transfer issue

**Comment by fobo66** [comment]
I've tried to update dependencies in instantsearch, but cannot test now in my app because of transitive dependencies

**Comment by fobo66** [comment]
I use Kotlin 1.3.72, and the is an [issue](https://github.com/Kotlin/kotlinx.serialization/issues/576) with kotlinx.serialization that is a reason of it and still not fixed

**Comment by Aallam** [comment]
Hello @fobo66,

Thank you for your reporting and contribution :)
Version [2.4.0-beta01](https://github.com/algolia/instantsearch-android/releases/tag/2.4.0-beta01) deployed, please try it.

**Comment by fobo66** [comment]
Hello @Aallam ! Just checked with the new version, it seems to work fine. Thank you!
