### ISSUE TITLE
Crashes in release build after upgrading to gradle 7.0.0

### ISSUE THREAD

**Issue by anderstechno** [algolia/instantsearch-android#253]
**Describe the bug 🐛**
After upgrading our app to use gradle 7.0.0 and releasing a new version, the app started crashing every time someone is firing a search:
`classpath 'com.android.tools.build:gradle:7.0.0'`

This does not happen when I run the app as debug locally.
I have just performed a git bisect so I am sure that the gradle version was the change that made it crash.
Reverting it to gradle 4.2.2 makes the crash go away

The stack trace looks like this when using a multi index search: 
```
Fatal Exception: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at com.algolia.search.endpoint.internal.EndpointMultipleIndexImpl.multipleQueries(EndpointMultipleIndexImpl.java:216)
       at com.algolia.search.endpoint.internal.EndpointMultipleIndexImpl$multipleQueries$1.invokeSuspend(EndpointMultipleIndexImpl.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at android.os.Handler.handleCallback(Handler.java:938)
       at android.os.Handler.dispatchMessage(Handler.java:99)
       at android.os.Looper.loop(Looper.java:246)
       at android.app.ActivityThread.main(ActivityThread.java:8512)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

And like this for a single index search: 
```
Fatal Exception: java.lang.ClassCastException: java.lang.Class cannot be cast to java.lang.reflect.ParameterizedType
       at com.algolia.search.endpoint.internal.EndpointSearchImpl.search(EndpointSearchImpl.java:244)
       at com.algolia.search.endpoint.internal.EndpointSearchImpl$search$1.invokeSuspend(EndpointSearchImpl.java:12)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:33)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at io.ktor.util.pipeline.SuspendFunctionGun.resumeRootWith(SuspendFunctionGun.java:191)
       at io.ktor.util.pipeline.SuspendFunctionGun.loop(SuspendFunctionGun.java:147)
       at io.ktor.util.pipeline.SuspendFunctionGun.access$loop(SuspendFunctionGun.java:15)
       at io.ktor.util.pipeline.SuspendFunctionGun$continuation$1.resumeWith(SuspendFunctionGun.java:93)
       at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(BaseContinuationImpl.java:46)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.java:106)
       at kotlinx.coroutines.EventLoopImplBase.processNextEvent(EventLoopImplBase.java:274)
       at kotlinx.coroutines.BlockingCoroutine.joinBlocking(BlockingCoroutine.java:85)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking(BuildersKt__BuildersKt.java:59)
       at kotlinx.coroutines.BuildersKt.runBlocking(BuildersKt.java:1)
       at kotlinx.coroutines.BuildersKt__BuildersKt.runBlocking$default(BuildersKt__BuildersKt.java:38)
       at kotlinx.coroutines.BuildersKt.runBlocking$default(BuildersKt.java:1)
       at com.algolia.instantsearch.helper.android.list.SearcherSingleIndexDataSource.loadInitial(SearcherSingleIndexDataSource.java:46)
       at androidx.paging.WrapperPageKeyedDataSource.loadInitial(WrapperPageKeyedDataSource.java:59)
       at androidx.paging.WrapperPageKeyedDataSource.loadInitial(WrapperPageKeyedDataSource.java:59)
       at androidx.paging.PageKeyedDataSource.dispatchLoadInitial(PageKeyedDataSource.java:339)
       at androidx.paging.ContiguousPagedList.<init>(ContiguousPagedList.java:175)
       at androidx.paging.PagedList.create(PagedList.java:216)
       at androidx.paging.PagedList$Builder.build(PagedList.java:388)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:206)
       at androidx.paging.LivePagedListBuilder$1.compute(LivePagedListBuilder.java:171)
       at androidx.lifecycle.ComputableLiveData$2.run(ComputableLiveData.java:101)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
       at java.lang.Thread.run(Thread.java:764)
```

**Comment by Aallam** [comment]
Hi @anderstechno,

Unfortunately, I couldn't reproduce your issue, did you try to update your Kotlin version and Gradle version (not the Android Gradle plugin)?

**Comment by anderstechno** [comment]
Thanks for the quick answer @Aallam. 
This is the combination of things that failed for me: 

**In project level build.gradle:**
`classpath 'com.android.tools.build:gradle:7.0.0'`
`classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.5.21"`

**In gradle-wrapper.properties:** 
`distributionUrl=https://services.gradle.org/distributions/gradle-7.1.1-all.zip`

Changing just the first one back to 4.2.2 and keeping the other ones works.

**Comment by Aallam** [comment]
What version of the lib are you using? did you try `2.11.0-beta02`?

**Comment by anderstechno** [comment]
2.10.0. I will test with the beta and let you know.

**Comment by anderstechno** [comment]
@Aallam It works with the beta and `gradle:7.0.0`. Any idea why that may be?

**Comment by Aallam** [comment]
`2.10.0` is built using AGP version `4.0.2`, while `2.11.0-beta02` is built using AGP version `7.0.0`.
