### ISSUE TITLE
Http client engine

### ISSUE THREAD

**Issue by sherif95** [algolia/instantsearch-android#360]
**Describe the bug 🐛**
I got the below crash many times on many devices. Could you please check it?

`Fatal Exception: kotlinx.coroutines.CoroutinesInternalError: Fatal exception in coroutines machinery for AwaitContinuation(DispatchedContinuation[Dispatchers.IO, Continuation at io.ktor.client.engine.HttpClientEngine$DefaultImpls.executeWithinCallContext(HttpClientEngine.kt:100)@dc9cc23]){Cancelled}@130c520. Please read KDoc to 'handleFatalException' method and report this incident to maintainers
       at kotlinx.coroutines.DispatchedTask.handleFatalException(DispatchedTask.kt:144)
       at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:115)
       at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:42)
       at kotlinx.coroutines.scheduling.TaskImpl.run(Tasks.kt:95)
       at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:570)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:750)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:677)
       at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:664)`

**Environment:**
 - OS: [android]
 - Library Version [3.1.3]

**Comment by Aallam** [comment]
Hey @sherif95, what version of Kotlin and coroutines are you using ?

**Comment by sherif95** [comment]
Hey Aallam,

Coroutines version -> 1.6.4
kotlin version -> 1.6.0

**Comment by ahmedElbarody** [comment]
@Aallam any support for this case ?

**Comment by afrencalg** [comment]
The HTTP client engine was replaced in 4.0.0 (Ktor migration). This class of crashes no longer applies.
