### ISSUE TITLE
NoClassDefFoundError jayway/jsonpath/Predicate

### ISSUE THREAD

**Issue by Haroenv** [algolia/instantsearch-android#76]
see originally https://github.com/algolia/instantsearch.js/issues/2895 by @martipello

---

just started getting this error this morning using the most recent version 

```
java.lang.NoClassDefFoundError: Failed resolution of: 
[Lcom/jayway/jsonpath/Predicate;     
at com.algolia.instantsearch.utils.JSONUtils.getObjectFromJSONPath(JSONUtils.java:40)
at com.algolia.instantsearch.utils.JSONUtils.getStringFromJSONPath(JSONUtils.java:22)
at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:473)
at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:409)
```

**Comment by PLNech** [comment]
Hi @martipello, thanks for reporting this! (and thanks @Haroenv for rerouting :wink:)

We had an issue in our release process that stripped the dependencies metadata before uploading to `mavenCentral`, which prevented to resolve them when building.

Release v1.7.24 fixes the issue. Updating to this version or higher should make this issue disappear, but please reopen this ticket if you still encounter it and I'll investigate your specific case!
