### ISSUE TITLE
NullPointerException in BindingViewHelper.java line 181

### ISSUE THREAD

**Issue by Hackertronix** [algolia/instantsearch-android#77]
I am using instant search on 2 different screens. Both screens **point to the same index** but have **different facet refinement values** and **different layout files for the hits item layout**. Instant search is working on the home screen which is a fragment but it's crashing on the other screen which is an activity. If I comment out/remove the home screen code, then the 2nd starts working again. I have attached the log below
```

java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getId()' on a null object reference
        at com.algolia.instantsearch.ui.databinding.BindingHelper.getFullAttribute(BindingHelper.java:181)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:473)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onBindViewHolder(Hits.java:409)
        at android.support.v7.widget.RecyclerView$Adapter.onBindViewHolder(RecyclerView.java:6673)
        at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6714)
        at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5647)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5913)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        at android.support.v7.widget.LinearLayoutManager.onLayoutChildren(LinearLayoutManager.java:614)
        at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3812)
        at android.support.v7.widget.RecyclerView.dispatchLayout(RecyclerView.java:3529)
        at android.support.v7.widget.RecyclerView.consumePendingUpdateOperations(RecyclerView.java:1737)
        at android.support.v7.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:4928)
        at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
        at android.view.Choreographer.doCallbacks(Choreographer.java:723)
        at android.view.Choreographer.doFrame(Choreographer.java:655)
        at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
        at android.os.Handler.handleCallback(Handler.java:790)
        at android.os.Handler.dispatchMessage(Handler.java:99)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
```

Please let me know if you need more details.

**Comment by PLNech** [comment]
Hi @Hackertronix, thank you for your report!

Could you give me a few details:

- Which version of InstantSearch are you using?

- It seems you are doing multi-index search (several search interfaces sharing the same SearchBox). If that's the case, did you:
  - [ ] Instantiate a pair of `Searcher` and `InstantSearch` for each interface with different **`variant`**
  - [ ] Set the right **`variant`** to each databound `View` 

We are still writing the guide for multi-index, but you can check the [Movies app](https://github.com/algolia/instantsearch-android-examples/tree/feat/moviesDemo#movies-application) that implements multi-index either as sections or as tabs.

**Comment by Hackertronix** [comment]
Hi,
I am not using multi-index search. I am actually using the same index on 2 screens but with different facet refinements. One of the screens does have a search box but the other screen is just a simple search on an Instant search helper

I am using InstantSearch v1.6.3

**Comment by PLNech** [comment]
Thanks for these details. 

From what I understand, the issue is that you are using two groups of Views in two different interfaces with the same `InstantSearch` without specifying a variant for each group.  

`Hits` [processes all databound views](https://github.com/algolia/instantsearch-android/blob/master/instantsearch/src/main/java/com/algolia/instantsearch/ui/views/Hits.java#L583) for its `variant`: as long as you don't specify any `variant`, any `Hits` will __pickup all your views__, which will ultimately cause an NPE when [binding its ViewHolder](https://github.com/algolia/instantsearch-android/blob/master/instantsearch/src/main/java/com/algolia/instantsearch/ui/views/Hits.java#L473) if some of your Views can be null at that time.

This is easy to fix: specifying `algolia:variant` on the Hits and each databound view (with a different variant name for your home screen Hits & Views and another for your fragment's Hits & Views). Let me know if this helps!

----

This being said, I'd like to understand better your use case: What's the purpose of each screen? Do you expect them to stay in sync when the user interacts with the other, or is each screen an independent search interface?

**Comment by Hackertronix** [comment]
I'm gonna have to check and get back on whether the variants attribute fixes it, as far as the purpose of the screen is concerned.... We have a large catalog of products, one the home screen we are adding a facet refinement which shows us the trending products in a list (no use of search here) on a different **independent** screen we have a search box where users can search across our catalog. We could have built the home screen the conventional REST call way, but that required exposing an endpoint on the server. Adding a refinement over the index was a no brainer.

**Comment by PLNech** [comment]
Hi @Hackertronix, thanks for your answer!

- Regarding variants, I'll be following this issue, let me know how it goes.

- Regarding your use case, it makes a lot of sense! Indeed, several of our customers use refinements to provide relevant products in a navigational experience. 

  With this use case in mind, I'm confident the variants system will resolve this issue: what we called `multi-index` is a pattern to enable several independent search interfaces to work alongside. Usually one would use two `Searcher` helpers, two `InstantSearch` helpers, and two sets of views, but in your case simply setting the variant for each view and their respective `Hits` should be enough as only one screen will be active at a given time.

**Comment by Hackertronix** [comment]
Hi @PLNech,
Sorry for the delayed response. 

Variants did seem to fix my issue. Thanks for pointing it out. One small feedback; in my opinion the document could be better structured to cover all of the features of InstantSearch instead of the bare minimum ones, required to get started. 

This would really help people in situations like these because honestly I spent way too much time scavenging the internet on how to fix the problem before deciding on opening an issue here 😅

**Comment by PLNech** [comment]
Hi Hackertronix, sorry for the delay as well. Glad to read variants solved your issue!

**Comment by PLNech** [comment]
Your feedback is on point, we know of some shortcomings in our documentation and are working on a new structure and more guides to cover various use-cases.

This being said, your thoughts could be very useful to help us improve our docs!
 - What kind of structure would be an improvement for you?
 - Which topics/features do you think should be covered further?
