### ISSUE TITLE
NullPointerException in HitsAdapter.ViewHolder when there are no data bindings in item layout used.

### ISSUE THREAD

**Issue by baniyaz** [algolia/instantsearch-android#85]
For my Hits widget, I have an item layout where I have used only custom views and no data bindings. This results in an NPE when HitsAdapter.ViewHolder is being initialised.  I did some debugging and found that the crash happens when it  attempts to iterate through a map of bindings which is null since I have no bindings in  my layout file.

I am able to stop the crash by adding a data binding to at least one  view in my item layout file. 

` java.lang.NullPointerException
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter$ViewHolder.<init>(Hits.java:580)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onCreateViewHolder(Hits.java:448)
        at com.algolia.instantsearch.ui.views.Hits$HitsAdapter.onCreateViewHolder(Hits.java:410)
        at android.support.v7.widget.RecyclerView$Adapter.createViewHolder(RecyclerView.java:6685)
        at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5869)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5752)
        at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5748)
        at android.support.v7.widget.LinearLayoutManager$LayoutState.next(LinearLayoutManager.java:2232)
        at android.support.v7.widget.LinearLayoutManager.layoutChunk(LinearLayoutManager.java:1559)
        at android.support.v7.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1519)
        `

**I am using version 1.8.4 of instantsearch-android**

**Comment by PLNech** [comment]
Hi @baniyaz, thanks for your report!

Indeed you should not need to use databound views for the Hits widget to work. I opened a PR with a fix resolving your issue, I'll let you know as soon as it's released.

I'm curious, why didn't you use the data binding views in the first place? Are there limitations in the current approach that prevented you to leverage it even for the most simple attributes? 
Your feedback will help us improve this mechanism :slightly_smiling_face:

**Comment by baniyaz** [comment]
Hello PLNech ,  Thank you for opening a PR so quickly.

I had to make some changes and checks on the data coming in before showing it in all my views.  

One example -  I  add a base_url for image paths but I can't use a prefix as the value of the prefix changes at runtime. My other views had similar constraints.

The data binding did work like a charm when I tried it though.

**Comment by PLNech** [comment]
Hey, you're welcome :slightly_smiling_face: 

Thanks for the feedback, that makes total sense! It's exactly for these kind of use-cases we have the `AlgoliaHitView` mechanism in place.

We are about to release the fix, I'll update you here with the new version!

**Comment by PLNech** [comment]
@baniyaz: [release 1.9.0 ships this fix along with some new features](https://github.com/algolia/instantsearch-android/releases/tag/1.9.0) :)
