### ISSUE TITLE
Error inflating class com.algolia.instantsearch.ui.views.Hits

### ISSUE THREAD

**Issue by radi-cho** [algolia/instantsearch-android#96]
**Do you want to request a *feature* or report a *bug*?** Bug

**Bug: What is the current behavior?**

I tried to use the instantearch Android library. Followed all the steps in [this guide](https://community.algolia.com/instantsearch-android/getting-started.html), but ended with an error.
> android.view.InflateException: Binary XML file line #47: Error inflating class com.algolia.instantsearch.ui.views.Hits

```
FATAL EXCEPTION: main
    java.lang.RuntimeException: Unable to start activity ComponentInfo: android.view.InflateException: Binary XML file line #47: Error inflating class com.algolia.instantsearch.ui.views.Hits
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2778)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: android.view.InflateException: Binary XML file line #47: Binary XML file line #47: Error inflating class com.algolia.instantsearch.ui.views.Hits
     Caused by: android.view.InflateException: Binary XML file line #47: Error inflating class com.algolia.instantsearch.ui.views.Hits
     Caused by: java.lang.reflect.InvocationTargetException
        at java.lang.reflect.Constructor.newInstance0(Native Method)
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334)
        at android.view.LayoutInflater.createView(LayoutInflater.java:647)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790)
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730)
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863)
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423)
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374)
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287)
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139)
        at com.rsg.SciSearch.MainActivity.onCreate(MainActivity.kt:30)
        at android.app.Activity.performCreate(Activity.java:7009)
        at android.app.Activity.performCreate(Activity.java:7000)
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:164)
        at android.app.ActivityThread.main(ActivityThread.java:6494)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
     Caused by: java.lang.IllegalStateException: Your View for attribute null must have an android:id.
        at com.algolia.instantsearch.ui.databinding.BindingHelper.mapAttribute(BindingHelper.java:166)
        at com.algolia.instantsearch.ui.databinding.BindingHelper.setVariantForView(BindingHelper.java:127)
        at com.algolia.instantsearch.ui.databinding.BindingHelper.setVariantForView(BindingHelper.java:100)
        at com.algolia.instantsearch.ui.views.Hits.<init>(Hits.java:142)
        at java.lang.reflect.Constructor.newInstance0(Native Method) 
        at java.lang.reflect.Constructor.newInstance(Constructor.java:334) 
        at android.view.LayoutInflater.createView(LayoutInflater.java:647) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:790) 
        at android.view.LayoutInflater.createViewFromTag(LayoutInflater.java:730) 
        at android.view.LayoutInflater.rInflate(LayoutInflater.java:863) 
        at android.view.LayoutInflater.rInflateChildren(LayoutInflater.java:824) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:515) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:423) 
        at android.view.LayoutInflater.inflate(LayoutInflater.java:374) 
        at android.support.v7.app.AppCompatDelegateImplV9.setContentView(AppCompatDelegateImplV9.java:287) 
        at android.support.v7.app.AppCompatActivity.setContentView(AppCompatActivity.java:139) 
        at com.rsg.SciSearch.MainActivity.onCreate(MainActivity.kt:30) 
        at android.app.Activity.performCreate(Activity.java:7009) 
        at android.app.Activity.performCreate(Activity.java:7000) 
        at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1214) 
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2731) 
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2856) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1589) 
        at android.os.Handler.dispatchMessage(Handler.java:106) 
        at android.os.Looper.loop(Looper.java:164) 
        at android.app.ActivityThread.main(ActivityThread.java:6494) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807) 
08-07 20:18:01.950 9885-9885/com.rsg.SciSearch E/CrashlyticsCore: Failed to execute task.
```

#### activity_main.xml
```
<?xml version="1.0" encoding="utf-8"?>
<LinearLayout
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:algolia="http://schemas.android.com/apk/res-auto"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    android:id="@+id/activity_main"
    android:orientation="vertical">
        <com.algolia.instantsearch.ui.views.Hits
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            algolia:itemLayout="@layout/hits_item"/>
    </LinearLayout>
```

> Note that there are comments above the LinearLayout in my actual code (in activity_main) so the line 47 displayed in the error is: 

```
<com.algolia.instantsearch.ui.views.Hits
```

#### hits_item.xml
```
<?xml version="1.0" encoding="utf-8"?>
<layout xmlns:algolia="http://schemas.android.com/apk/res-auto">
    <LinearLayout xmlns:android="http://schemas.android.com/apk/res/android"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:orientation="horizontal">

        <ImageView
            android:id="@+id/product_image"
            android:layout_width="100dp"
            android:layout_height="100dp"
            android:layout_margin="10dp"
            android:scaleType="fitCenter"
            algolia:attribute='@{"image"}'/>

        <TextView
            android:id="@+id/product_name"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            algolia:attribute='@{"name"}'/>

        <TextView
            android:id="@+id/product_price"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            algolia:attribute='@{"salePrice"}'/>
    </LinearLayout>
</layout>
```

#### MainActivity.kt
```
class MainActivity : AppCompatActivity() {
    private val ALGOLIA_APP_ID = "latency"
    private val ALGOLIA_SEARCH_API_KEY = "3d9875e51fbd20c7754e65422f7ce5e1"
    private val ALGOLIA_INDEX_NAME = "bestbuy"

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val searcher = Searcher.create(ALGOLIA_APP_ID, ALGOLIA_SEARCH_API_KEY, ALGOLIA_INDEX_NAME)
        val helper = InstantSearch(this, searcher)
        helper.search()
    }
}
```

### Please help me resolve this issue.

**Comment by radi-cho** [comment]
I found two mistakes in my code:

1. **Missing context.** My Linear layout had no context attribute.
2. **Missing id.** My algolia Hits element was missing id.

Fixing these mistakes solved the main issue.

**Comment by PLNech** [comment]
Thanks for your report and sharing the root cause! I'll take care of ensuring our getting started guide mentions to add both. 

Let us know if we can help further :)
